/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Type = string;
export type NDofs = number;
export type NQs = number;
export type DofsLimit = number[][];
export type Name1 = string;
export type Idx = number;
export type VisMode = string;
export type VisualizeContact = boolean;
export type NDofs1 = number | null;
export type NQs1 = number | null;
export type Joints = JointInfo[] | null;
export type QNames = string[] | null;
export type QLimitsLower = number[] | null;
export type QLimitsUpper = number[] | null;
export type QIsQuaternion = boolean[] | null;
export type QuatGroups = number[][] | null;
export type HasFreeJoint = boolean | null;
export type FreeJointQStart = number | null;
export type Qpos = number[] | null;
export type Shadows = boolean;
export type WorldFrame = boolean;
export type LinkFrame = boolean;
export type LinkFrameSize = number;
export type CameraFrustum = boolean;
export type FaceNormals = boolean;
export type VertexNormals = boolean;
export type Wireframe = boolean;
export type Orthographic = boolean;
export type Pos = number[] | null;
export type Lookat = number[] | null;
export type Fov = number | null;
export type ViewMatrix = number[] | null;
export type ProjMatrix = number[] | null;
export type Idx1 = number;
export type Qpos1 = number[];
export type Type1 = "scene_info";
export type Entities = EntityInfo[];
export type NEnvs = number;
export type SimDt = number;
export type Type2 = "state_update";
export type Time = number;
export type Step = number;
export type Fps = number;
export type Paused = boolean;
export type EntityPositions = EntityPosition[] | null;
export type Type3 = "sim_control";
export type Action = "play" | "pause" | "step" | "reset";
export type Type4 = "camera_update";
export type Action1 = "orbit" | "pan" | "zoom" | "set_pose" | "set_fov" | "reset";
export type DAzimuth = number | null;
export type DElevation = number | null;
export type Dx = number | null;
export type Dy = number | null;
export type Factor = number | null;
export type Pos1 = number[] | null;
export type Lookat1 = number[] | null;
export type Fov1 = number | null;
export type Type5 = "entity_update";
export type EntityIdx = number;
export type Qpos2 = number[] | null;
export type NormalizeQuats = boolean | null;
export type QuatGroups1 = number[][] | null;
export type DofIdx = number | null;
export type Value = number | null;
export type VisMode1 = ("visual" | "collision") | null;
export type Wireframe1 = boolean | null;
export type ContactViz = boolean | null;
export type Type6 = "vis_toggle";
export type Property = string;
export type Value1 = boolean | number | string;
export type Type7 = "set_resolution";
export type Width = number;
export type Height = number;
export type Type8 = "set_target_fps";
export type Fps1 = number;

export interface ProtocolSchema {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ProtocolSchema`'s JSON-Schema
 * via the `definition` "JointInfo".
 */
export interface JointInfo {
  name: Name;
  type: Type;
  n_dofs: NDofs;
  n_qs: NQs;
  dofs_limit: DofsLimit;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ProtocolSchema`'s JSON-Schema
 * via the `definition` "EntityInfo".
 */
export interface EntityInfo {
  name: Name1;
  idx: Idx;
  vis_mode?: VisMode;
  visualize_contact?: VisualizeContact;
  n_dofs?: NDofs1;
  n_qs?: NQs1;
  joints?: Joints;
  q_names?: QNames;
  q_limits_lower?: QLimitsLower;
  q_limits_upper?: QLimitsUpper;
  q_is_quaternion?: QIsQuaternion;
  quat_groups?: QuatGroups;
  has_free_joint?: HasFreeJoint;
  free_joint_q_start?: FreeJointQStart;
  qpos?: Qpos;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ProtocolSchema`'s JSON-Schema
 * via the `definition` "VisState".
 */
export interface VisState {
  shadows?: Shadows;
  world_frame?: WorldFrame;
  link_frame?: LinkFrame;
  link_frame_size?: LinkFrameSize;
  camera_frustum?: CameraFrustum;
  face_normals?: FaceNormals;
  vertex_normals?: VertexNormals;
  wireframe?: Wireframe;
  orthographic?: Orthographic;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ProtocolSchema`'s JSON-Schema
 * via the `definition` "CameraState".
 */
export interface CameraState {
  pos?: Pos;
  lookat?: Lookat;
  fov?: Fov;
  view_matrix?: ViewMatrix;
  proj_matrix?: ProjMatrix;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ProtocolSchema`'s JSON-Schema
 * via the `definition` "EntityPosition".
 */
export interface EntityPosition {
  idx: Idx1;
  qpos: Qpos1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ProtocolSchema`'s JSON-Schema
 * via the `definition` "SceneInfoMsg".
 */
export interface SceneInfoMsg {
  type?: Type1;
  entities: Entities;
  vis_state?: VisState1;
  camera_state?: CameraState1;
  n_envs?: NEnvs;
  sim_dt?: SimDt;
  [k: string]: unknown;
}
export interface VisState1 {
  shadows?: Shadows;
  world_frame?: WorldFrame;
  link_frame?: LinkFrame;
  link_frame_size?: LinkFrameSize;
  camera_frustum?: CameraFrustum;
  face_normals?: FaceNormals;
  vertex_normals?: VertexNormals;
  wireframe?: Wireframe;
  orthographic?: Orthographic;
  [k: string]: unknown;
}
export interface CameraState1 {
  pos?: Pos;
  lookat?: Lookat;
  fov?: Fov;
  view_matrix?: ViewMatrix;
  proj_matrix?: ProjMatrix;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ProtocolSchema`'s JSON-Schema
 * via the `definition` "StateUpdateMsg".
 */
export interface StateUpdateMsg {
  type?: Type2;
  time?: Time;
  step?: Step;
  fps?: Fps;
  paused?: Paused;
  camera_state?: CameraState | null;
  entity_positions?: EntityPositions;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ProtocolSchema`'s JSON-Schema
 * via the `definition` "SimControlMsg".
 */
export interface SimControlMsg {
  type?: Type3;
  action: Action;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ProtocolSchema`'s JSON-Schema
 * via the `definition` "CameraUpdateMsg".
 */
export interface CameraUpdateMsg {
  type?: Type4;
  action: Action1;
  d_azimuth?: DAzimuth;
  d_elevation?: DElevation;
  dx?: Dx;
  dy?: Dy;
  factor?: Factor;
  pos?: Pos1;
  lookat?: Lookat1;
  fov?: Fov1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ProtocolSchema`'s JSON-Schema
 * via the `definition` "EntityUpdateMsg".
 */
export interface EntityUpdateMsg {
  type?: Type5;
  entity_idx: EntityIdx;
  qpos?: Qpos2;
  normalize_quats?: NormalizeQuats;
  quat_groups?: QuatGroups1;
  dof_idx?: DofIdx;
  value?: Value;
  vis_mode?: VisMode1;
  wireframe?: Wireframe1;
  contact_viz?: ContactViz;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ProtocolSchema`'s JSON-Schema
 * via the `definition` "VisToggleMsg".
 */
export interface VisToggleMsg {
  type?: Type6;
  property: Property;
  value: Value1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ProtocolSchema`'s JSON-Schema
 * via the `definition` "SetResolutionMsg".
 */
export interface SetResolutionMsg {
  type?: Type7;
  width: Width;
  height: Height;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ProtocolSchema`'s JSON-Schema
 * via the `definition` "SetTargetFpsMsg".
 */
export interface SetTargetFpsMsg {
  type?: Type8;
  fps: Fps1;
  [k: string]: unknown;
}
