"""Auto-generated by qipc.codegen."""

import math

import quadrants as qd
from quadrants.types.annotations import template

# ABD orthogonality energy: analytic eigensystem helpers
# Psi = kappa * sum_i (sigma_i^2 - 1)^2
# See docs/design/architecture.md


@qd.func
def abd_ortho_dPsi_dsigma(R: template(), kappa: qd.f64, sigma: qd.types.vector(3, qd.f64)):
    x0 = 4 * kappa
    R[0] = sigma[0] * x0 * (qd.pow(sigma[0], 2) - 1)
    R[1] = sigma[1] * x0 * (qd.pow(sigma[1], 2) - 1)
    R[2] = sigma[2] * x0 * (qd.pow(sigma[2], 2) - 1)


def host_abd_ortho_dPsi_dsigma(kappa, sigma):
    x0 = 4 * kappa
    return [
        sigma[0] * x0 * (math.pow(sigma[0], 2) - 1),
        sigma[1] * x0 * (math.pow(sigma[1], 2) - 1),
        sigma[2] * x0 * (math.pow(sigma[2], 2) - 1),
    ]


@qd.func
def abd_ortho_d2Psi_dsigma2(R: template(), kappa: qd.f64, sigma: qd.types.vector(3, qd.f64)):
    x0 = qd.pow(sigma[0], 2)
    x1 = 8 * kappa
    x2 = 4 * kappa
    x3 = qd.pow(sigma[1], 2)
    x4 = qd.pow(sigma[2], 2)
    R[0] = x0 * x1 + x2 * (x0 - 1)
    R[1] = x1 * x3 + x2 * (x3 - 1)
    R[2] = x1 * x4 + x2 * (x4 - 1)


def host_abd_ortho_d2Psi_dsigma2(kappa, sigma):
    x0 = math.pow(sigma[0], 2)
    x1 = 8 * kappa
    x2 = 4 * kappa
    x3 = math.pow(sigma[1], 2)
    x4 = math.pow(sigma[2], 2)
    return [x0 * x1 + x2 * (x0 - 1), x1 * x3 + x2 * (x3 - 1), x1 * x4 + x2 * (x4 - 1)]
